name: Cleanup CF

on:
    pull_request:
        types: [closed]

jobs:
    cleanup_job:
        runs-on: ubuntu-latest
        steps:
            - name: Delete website previews
              run: |
                  deployments=$(curl -X GET "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/shine-web/deployments" \
                    -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
                    -H "Accept: application/json")
                  id_list=$(echo $deployments | jq -r --arg bn "${{ github.head_ref }}" '.result[] | select(.deployment_trigger.metadata.branch == $bn) | .id')
                  for id in $id_list; do
                    echo "Deleting deployment $id"
                    curl -X DELETE "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/shine-web/deployments/$id?force=true" \
                      -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
                      -H "Accept: application/json"
                  done
