name: Cleanup R2

on:
    workflow_dispatch:

env:
    BUCKET_LINK: https://ce847ac4c44fb11af63e62ba34ec40db.r2.cloudflarestorage.com
    BUCKET_NAME: shine-assets

jobs:
    cleanup:
        runs-on: ubuntu-latest
        steps:
            - name: Setup AWS CLI
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: auto
              run: |
                  aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
                  aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
                  aws configure set default.region "$AWS_DEFAULT_REGION"

            - name: Read latest.json
              id: read_latest
              run: |
                  aws s3 cp s3://${BUCKET_NAME}/latest.json ./latest.json --endpoint-url=${BUCKET_LINK}
                  VERSION=$(jq -r '.version' latest.json)
                  echo "LATEST_VERSION=$VERSION" >> $GITHUB_ENV

            - name: Delete old folders
              run: |
                  aws s3 ls s3://${BUCKET_NAME}/ --endpoint-url=${BUCKET_LINK} \
                    | awk '{print $2}' \
                    | grep -vE "${LATEST_VERSION}|fixed|latest\.json" \
                    | while read -r folder; do
                        if [ -n "$folder" ]; then
                          aws s3 rm "s3://${BUCKET_NAME}/${folder}" --recursive --endpoint-url=${BUCKET_LINK}
                        fi
                      done
